# Generated by Django 4.1.7 on 2023-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cloths_image_alter_electronics_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloths',
            name='image',
            field=models.ImageField(upload_to='cloth_images'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='image',
            field=models.ImageField(upload_to='Electroic_images'),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='image',
            field=models.ImageField(upload_to='Electroic_images'),
        ),
    ]
