# Generated by Django 4.1.7 on 2023-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cloths_image_alter_electronics_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.CreateModel(
            name='SCloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.CreateModel(
            name='TCloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.CreateModel(
            name='WCloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cloths',
            new_name='Computer',
        ),
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Laptop',
        ),
    ]
