# Generated by Django 4.1.7 on 2023-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mobile_scloths_tcloths_wcloths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kangans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.CreateModel(
            name='Necklaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='All_images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Jewellery',
            new_name='Jumkas',
        ),
    ]
