# Generated by Django 4.1.7 on 2023-03-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_kangans_necklaces_rename_jewellery_jumkas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TCloths',
            new_name='ShirtCloths',
        ),
        migrations.RenameModel(
            old_name='SCloths',
            new_name='TshirtCloths',
        ),
        migrations.RenameModel(
            old_name='WCloths',
            new_name='WomenCloths',
        ),
    ]
